services:
  health-monitor:
    build: .
    container_name: health-monitor
    restart: unless-stopped
    
    environment:
      - HOST=localhost
      - PORT=80
      - ENDPOINT=/health
      - CONTAINER_NAME=app
      - CHECK_INTERVAL=30
      - TIMEOUT=10
      - MAX_ATTEMPTS=3
      - COOLDOWN=300
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock